### ISSUE TITLE
Return path of icon

### ISSUE THREAD

**Issue by nathanaelphilip** [visualfanatic/vue-svg-loader#14]
I think in the earlier versions of vue-svg-loader, if you used the imported Icon inside your .vue <script>, it would return the path to the icon. That seems to have stopped – is there a way to re-implement that? Or is there a way for me to get that from the returned object?

**Comment by nathanaelphilip** [comment]
Or is there a way to just render out the HTML? from the returned vue-template-compiler object?

**Comment by nathanaelphilip** [comment]
@visualfanatic just pinging because this is a pretty big blocker for me. I know you have other things, but if you could look at this soon, I would appreciate it – bigly.

**Comment by visualfanatic** [comment]
Merged & published as `v0.4.0`

**Comment by nathanaelphilip** [comment]
Thank you so much @visualfanatic !

**Comment by steveops** [comment]
Hi all, am trying to use an svg as a background image like this: 
```
div{
   background-image: url(my-icon.svg)
}
```
This doesnt seem to work and upon inspecting the element, I see this: 
<img width="296" alt="screen shot 2018-01-06 at 02 22 56" src="https://user-images.githubusercontent.com/12711215/34632784-9509deaa-f288-11e7-9ebb-dc90f12199b6.png">
How can I solve this?

**Comment by visualfanatic** [comment]
@steveops Please use `url-loader` if you want to use SVG files in CSS.
@nathanaelphilip I am preparing a new version of `vue-svg-loader` and I was wondering what type of path you were looking for before creating this issue. Relative or absolute? I am asking, because right now this loader gives you a relative path to file, but next release would break that and return an absolute path.
