### ISSUE TITLE
How to add it to Jest configuration?

### ISSUE THREAD

**Issue by koresar** [visualfanatic/vue-svg-loader#38]
The `MyComponent` is importing an SVG file, and then using it in the code. I cannot unit test such component because vue-svg-loader is not configured in my Jest.

```js
import { shallowMount } from "@vue/test-utils";
import MyComponent from "../MyComponent";

describe("MyComponent.vue", () => {
    it("should put new date if is was passed via props", async () => {
        const wrapper = shallowMount(Login, {
            propsData: {
                value: "2018-01-05"
            }
        });
```

The unit test throws... Cannot render the SVG.

How to add `vue-svg-loader` to the Jest configuration?

**Comment by visualfanatic** [comment]
There is one major issue when it comes to integrating `vue-svg-loader` with Jest, and it is async behaviour. Jest's transforms are synchronous, webpack loaders can be both. That means we cannot use SVGO to process the SVG files, which can be bad in some cases. I suggest you and everybody to always pass the SVG files through SVGO before putting them in a project [(for example using this great tool)](https://jakearchibald.github.io/svgomg/), so that the end result does not contain:
- XML declaration,
- `<script>` tags,
- `<style>` tags.

If your SVGs are prepared, create a transform file named for example `svgTransform.js` with:
```js
const vueJest = require('vue-jest/lib/template-compiler');

module.exports = {
  process(content) {
    const { render } = vueJest({
      content,
      attrs: {
        functional: false,
      },
    });

    return `module.exports = { render: ${render} }`;
  },
};
```

And then modify your `jest.config.js` to use the transform file above (note that `<rootDir>` is injected by Jest):
```js
module.exports = {
  transform: {
    '^.+\\.svg$': '<rootDir>/path/to/svgTransform.js',
  },
};
```

To test if everything works you need to start the tests with the `--no-cache` flag. Let me know if that works for you.

**Comment by visualfanatic** [comment]
@koresar have you had a chance to test the solution above?

**Comment by koresar** [comment]
Hello.

Sorry mate. I had no chance.

We've decided to just rename the file extension from .svg to .vue and wrap
it in the <template> tag. As the result no additional configuration needed
anywhere.

Cheers

**Comment by visualfanatic** [comment]
No problem at all 👍

**Comment by joelworsham** [comment]
Just wanted to say that I also had this error, and your solution works like a charm with no modification 👍 

Thanks!

**Comment by sarahdayan** [comment]
@koresar If that didn't work for you, check whether `svg` is present in another regular expression in other `transform` properties.

If you're using Vue CLI, it probably generated a line for all assets (including SVGs) that gets transformed with `jest-transform-stub`. If this line contains `svg`, just remove it, it should work.

```js
module.exports = {
  // ...
  transform: {
    // ...
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    '^.+\\.svg$': '<rootDir>/svgTransform.js'
  }
}
```

**Comment by engmagdy87** [comment]
I follow the instruction of adding loader to jest
https://vue-svg-loader.js.org/faq.html#how-to-use-this-loader-with-jest 

but this error appears

![Screenshot-20191009142507-708x279](https://user-images.githubusercontent.com/8473421/66481210-a7a84300-eaa0-11e9-8286-7648479785b4.png)

**Comment by hendrikras** [comment]
any update on this? Im running into the exact same error.

**Comment by fameches** [comment]
> I follow the instruction of adding loader to jest
> https://vue-svg-loader.js.org/faq.html#how-to-use-this-loader-with-jest
> 
> but this error appears
> 
> ![Screenshot-20191009142507-708x279](https://user-images.githubusercontent.com/8473421/66481210-a7a84300-eaa0-11e9-8286-7648479785b4.png)


if your svg files have <?xml ?> you'll get the error.
const vueJest = require('vue-jest/lib/template-compiler');

module.exports = {
  process (content) {
    // remove <?xml ?>. Should be one root element or get an error
    if (content.startsWith('<?xml')) {
      const svgElIndex = content.indexOf('?>') + 2;
      content = content.substring(svgElIndex);
    }

    const { render } = vueJest({
      content,
      attrs: {
        functional: false
      }
    });

    return `module.exports = { render: ${render} }`;
  }
};

**Comment by kylegoines** [comment]
> if your svg files have ?xml ? you'll get the error. So need just remove it:

i removed my ?xml and still am encountering the above issue  
- @fameches im trying to replicate your code but it seems there are some syntax errors and i dont understand what you're trying to get across

**Comment by anandbhaskaran** [comment]
Solution from @visualfanatic worked! However as I was using a later version of babel, I had to install babel bridge to make vue-jest compile properly. 

npm i -D babel-core@^7.0.0-bridge.0

**Comment by joaopslins** [comment]
Hi folks,

This solution is not working anymore after updating to `vue-jest@4`, or `@vue/vue2-jest` because this import fails `require('vue-jest/lib/template-compiler');`, since there's no `template-compiler` file anymore.

Does anyone figured out another workaround? Thanks!

**Comment by anthonylebrun** [comment]
@joaopslins It took a bit of digging, but here's how I got this working for `@vue/vue2-jest` and `jest 28`:

Update `svgTransform.js` to:
```
const VueTemplateCompiler = require('vue-template-compiler');

module.exports.process = (svgSource, filename) => {
  const result = VueTemplateCompiler.compileToFunctions(
    `${svgSource}`
  );

  return {
    code: `module.exports = { render: ${result.render} }`,
  };
}
```

jest.config.js stays the same:

```
module.exports = {
  transform: {
    '^.+\\.svg$': '<rootDir>/path/to/svgTransform.js',
  },
};
```

And as @visualfanatic pointed out, make sure you run jest with the `--no-cache` flag option i.e.

```
jest --no-cache
```

Otherwise you may not see any impact after updating `svgTransform.js`. I didn't realize jest was caching the transforms at first when I was trying to debug and wasted a good few hours because of it.

For reference:
- https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#compilercompiletofunctionstemplate
- https://jestjs.io/docs/28.0/code-transformation

**Comment by anthonylebrun** [comment]
As a sidenode, make sure to run [--clearCache](https://jestjs.io/docs/cli#--clearcache) after you make this change... Since `--no-cache` only skips the cache and doesn't reset it, you maybe experience stale issues even after fixing your `svgTransform.js` if you don't reset it explicitly.

**Comment by joaopslins** [comment]
@anthonylebrun Thank you! This worked well! I appreciate the help 🙇
