### ISSUE TITLE
Cannot trigger @click event on svg component tag

### ISSUE THREAD

**Issue by srbiotik** [visualfanatic/vue-svg-loader#54]
I am using the latest version of the loader and I am loving the ease and an uncluttered zen feeling it brings comparing to just using SVG inline, not to mention the hot reload benefits.
However the v-on:click directive does not work, and bear in mind I am unsure if this is a bug, was never a feature, or my configuration is somehow off.
I configured both Webpack and Vue using offered documentation, and am able to import SVG file and place it's component tag to component HTML. It does when you use it on an SVG element/tag natively.

**Comment by mmieluch** [comment]
Have you tried using `v-on:click.native`?

**Comment by srbiotik** [comment]
No, I will try and report the outcome.

**Comment by FistMeNaruto** [comment]
Facing the same issue, `@click.native` does not work.

**Comment by sunnyskc** [comment]
same here `@click.native` was working until 0.10.0

**Comment by mmieluch** [comment]
Components generated by this loader are functional. I believe the only way to listen to events on functional components is to define them explicitly in the component itself. Since we don't have control over the automatically transformed SVG component, the only way to go is to wrap your components in outer tags and listen to events on the wrappers instead of components themselves.

**Comment by tamasf97** [comment]
@visualfanatic The `vue-svg-loader@next` branch seems to have solved the issue, at least it works fine for every event I throw at it.

**Comment by dcrystalj** [comment]
this solved issue for me as well.

**Comment by Kivol** [comment]
@visualfanatic Is there any schedule for it to be merged to mainstream?

**Comment by visualfanatic** [comment]
Yes, I just released it as `v0.12.0` :)
